--- #YAML:1.0
name: X500-DN-Parser
version: 1.16
author:
  - Ron Savage <ron@savage.net.au>
abstract: Parse X500 Distinguished Names
license: artistic
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
